---
type: showroom

# Set the left content column width to 40%
default_width: 40
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: Terminal
    path: /wetty
    port: 443
  - name: OpenShift Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: Red Hat Advanced Cluster Security
    url: 'https://central-reencrypt-stackrox.${DOMAIN}'
  - name: OpenShift GitOps
    url: 'https://openshift-gitops-server-openshift-gitops.${DOMAIN}'
  - name: SSO (Keycloak)
    url: 'https://sso.${DOMAIN}/realms/tpa/account/'
    external: true
  - name: RHTPA
    url: 'https://server-trusted-profile-analyzer.${DOMAIN}'
  - name: Nexus
    url: 'https://nexus-lightwell-repo.${DOMAIN}'
    external: true
  - name: Gitea
    url: 'https://gitea.${DOMAIN}'
    external: true
  - name: Developer Hub
    url: 'https://backstage-developer-hub-rhdh.${DOMAIN}'
    external: true
